[[plugins]]
repo = 'Shougo/denite.nvim'
hook_post_source = '''
  call denite#custom#alias('source', 'file_rec/git', 'file_rec')
  call denite#custom#var('file_rec/git', 'command', ['git', 'ls-files', '-co', '--exclude-standard'])
  nnoremap <silent> <C-p> :<C-u>Denite `finddir('.git', ';') != '' ? 'file_rec/git' : 'file_rec'` -highlight-mode-insert=Search<CR>
'''
