[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # Git連携
repo = 'tpope/vim-fugitive'

[[plugins]] # 括弧の自動挿入
repo = 'cohama/lexima.vim'

[[plugins]] # ステータスライン
repo = 'itchyny/lightline.vim'

[[plugins]] # Comment out
repo = 'tomtom/tcomment_vim'

# Lang

[[plugins]] # Haml
repo  = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]] # Html5
repo  = 'othree/html5.vim'
on_ft = 'html'

[[plugins]] # Toml
repo  = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # Markdown
repo = 'rcmdnk/vim-markdown'
on_ft = ['markdown','mkd']
hook_add = '''
    let g:vim_markdown_frontmatter = 1
    let g:vim_markdown_math = 1
'''

[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = 'coffee'

[[plugins]] # Japanese doc
repo = 'vim-jp/vimdoc-ja'
on_ft = 'help'
hook_add = '''
    set helplang=ja,en
'''

# Colors

[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
	au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

